### ISSUE TITLE
Add image to readme

### ISSUE THREAD

**Issue by hailwood** [plastyk/silverstripe-dashboard#12]
You'll get a higher adoption rate if you add an image to your readme :)

**Comment by 3Dgoo** [comment]
Sounds good. I'll add a screen shot when I get some free time.

**Comment by hailwood** [comment]
Woah! This thing is pretty! Good job.

**Comment by 3Dgoo** [comment]
Thanks and thanks for submitting the issue. If you have any other ideas feel free to post more issues.
