### ISSUE TITLE
Change panel accent colour code

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#15]
It is nice to customise the panel colour for each client site to tie it in with the site's colour scheme. This give the dashboard a nice personal touch. 

Right now we do this with the following code:

**mysite/css/dashboard-cms.css**

	.cms-content.DashboardAdmin .dashboard-panel {
		border-top-color: #0093d1 !important;
	}

**config.yml**

    LeftAndMain:
      extra_requirements_css:
        - 'mysite/css/dashboard-cms.css'

Let's make this easier by adding a config variable to change the panel accent colour like so:

    DashboardAdmin:
      panel_accent_colour: '#0093d1'

Also, we should add documentation explaining how to do this and showing an example screen shot.

- [x] Add `panel_accent_colour` config code
- [x] Add `panel_accent_colour` documentation
- [x] Add `panel_accent_colour` screenshot

**Comment by 3Dgoo** [comment]
@Turnerj I was thinking. Should the variable be `panel_accent_colour` or `panel_accent_color`? In the web world `color` is usually used over `colour`. What do you think?

**Comment by Turnerj** [comment]
Yeah, we probably shouldn't fight it. Let's make it be `color` to match other CSS declarations.

**Comment by 3Dgoo** [comment]
Or should we allow either?
