### ISSUE TITLE
Search doDashboardSearch changes

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#25]
Regarding the search and how we call `performSearch`, is our interface here intuitive? 

When calling `performSearch` the function returns a list of results, but then we don't use them. We store the results against the `DashboardSearchResultPanel` class and then use that when we call `forTemplate`.

Maybe we should change this so our call to `forTemplate` could take the search results as a parameter rather than using the results property. 

As mentioned in #24

**Comment by Turnerj** [comment]
Relates to #76 - let's do the changes at the same time.
