### ISSUE TITLE
Add Translation Support

### ISSUE THREAD

**Issue by Turnerj** [plastyk/silverstripe-dashboard#3]
Add translation support like how other SilverStripe modules do.
https://www.transifex.com/

Things to translate:

- [x] `RecentlyEditedPagesPanel`
- [x] `RecentlyCreatedPagesPanel`
- [x] `UpdatePanel`
- [x] `MoreInformationPanel`
- [x] `UsefulLinksPanel`
- [x] `SearchPanel`

**Comment by Turnerj** [comment]
@3Dgoo, do you want to note here the other parts we need to do for "completing" translation support?

**Comment by 3Dgoo** [comment]
Things to translate:

- [ ] RecentlyEditPagesPanel
- [ ] RecentlyCreatedPagesPanel
- [ ] UpdatePanel
- [ ] MoreInformationPanel
- [ ] UsefulLinksPanel
- [ ] SearchPanel

**Comment by Turnerj** [comment]
Just some issues left with non-EN characters in YML files we need to sort out.

**Comment by 3Dgoo** [comment]
I've created a new issue to track the de.yml issue #44
