### ISSUE TITLE
Recently edited pages / recently created pages date wrap

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#41]
On the recently edited pages / recently created pages panels when a page has a long title or a long breadcrumb it can force the created date / edited date column to shrink down to a point where the date information wraps.

I think this looks crap:
![date-wrap-screenshot](https://user-images.githubusercontent.com/2616373/26956038-24716cc8-4cfa-11e7-95e2-e7944efc3d88.png)

I suggest we make it that this column never wraps like so:
![date-nowrap-screenshot](https://user-images.githubusercontent.com/2616373/26956036-2094ee2c-4cfa-11e7-9267-a8f3e2922d0e.png)

What do you think @RuthAdele @Turnerj

**Comment by RuthAdele** [comment]
Agreed.

**Comment by Turnerj** [comment]
Agreed! (Though my email notification had the images the other way around lol)
