### ISSUE TITLE
Incorrect usage of _t in DashboardAdmin

### ISSUE THREAD

**Issue by Turnerj** [plastyk/silverstripe-dashboard#52]
see https://scrutinizer-ci.com/g/plastyk/silverstripe-dashboard/issues/master/files/code/admin/DashboardAdmin.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-80505571

**Comment by Turnerj** [comment]
Issue raised in framework regarding translation API: silverstripe/silverstripe-framework#7018

**Comment by 3Dgoo** [comment]
Fixed
