### ISSUE TITLE
Documentation php code highlighting

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#83]
Our php code is not highlighted in our documentation:
https://plastyk.github.io/silverstripe-dashboard/en/customisation-new-panels
https://plastyk.github.io/silverstripe-dashboard/en/customisation-quicklinks

This is due to this:
https://stackoverflow.com/questions/16895051/how-to-syntax-highlight-php-in-the-github-wiki

Here is a ticket for this issue:
https://github.com/github/markup/issues/107

**Comment by 3Dgoo** [comment]
It looks like this is a known bug.

@Turnerj should we put `<?php` in our documentation while this issue is not fixed?

**Comment by Turnerj** [comment]
Yeah, I reckon it might be best.
