### ISSUE TITLE
Fix for explicitly sized dynamic panel

### ISSUE THREAD

**Issue by OldStarchy** [plastyk/silverstripe-dashboard#87]
Creating a panel with a Chart.js graph I ran into an issue with panel resizing.

![problemo](https://user-images.githubusercontent.com/15243523/28151844-5bc6c5fe-67dc-11e7-988e-fcce41b66e17.gif)

When the panel grows the graph resizes to fit, but the explicit size of the graph prevents the panel from shrinking back down. Adding `overflow: auto;` to the panel class (dashboard.css line 20) solves this issue.

This case is obviously specific to the panels I'm making, however its not unreasonable to think that this issue would appear with other dynamic objects too. As I can't see any potential downsides using this fix on panels that don't have this issue, I thought it made sense to add it to the dashboard module directly, rather than adding it individually as fix to all panels that contain such content.

**Comment by 3Dgoo** [comment]
That is an interesting bug. While I think this bug may be unique to this graph JavaScript, I don't see any downside to including this bit off css in the main `dashboard.css` file. 

Do you want to put in a pull request for this change?

**Comment by 3Dgoo** [comment]
From our discussion to me it seems this JavaScript graph drawing bug is caused by using `flex-basis`.
`overflow: auto;` fixes the bug, but the issue is still that we are using `flex-basis`

Lets replace `flex-basis` with `width`. 

@aNickzz did you want to make this change and submit a pull request for it?
