### ISSUE TITLE
Move to Grid Layout

### ISSUE THREAD

**Issue by Turnerj** [plastyk/silverstripe-dashboard#88]
Allows greater flexibility in laying out the panels rather than us needing to define custom CSS just to make a panel twice as wide.

We would need to identify how best we should approach this (eg. native CSS or something like [Simple Grid](http://simplegrid.io/)). Also, check to see if SS4 has a grid library on anything natively.

Not sure about aiming this for 1.0 though at the same time, this would be a breaking change and would need a major version number bump.

Thoughts @3Dgoo ?

**Comment by OldStarchy** [comment]
Probably worth mentioning that this would likely solve #87.

**Comment by Turnerj** [comment]
This does affect #37 as documetation/examples/screenshots should be adjusted to show use with a grid layout.
