### ISSUE TITLE
Extend UpdatePanel version number support

### ISSUE THREAD

**Issue by Turnerj** [plastyk/silverstripe-dashboard#89]
Currently the panel has issues with non-release versions of SilverStripe (eg. when we flag `dev-master` in `composer.json`).

I think we could display a different message when we don't know the full version. So if it was `3.6.*`, we say that there _may_ be an update. We would have this controllable via YML or even potentially have this connected to a timeout of sorts (so if it has been 60 days, we might show the message).

When there is a major or minor update, the normal messages would still display.

Alternatively, we could just make ignore from that particular point in the version number string (so in my example, the patch versions would be ignored). Obviously there are downsides to this as patch versions are bug and security fixes but unfortunately it isn't that we can just read the `git` folder to pull the commit version.

I think we should do something about this so we can specify `3.6.*` as a version number in composer while still allowing the person to know when updates are available.

**Comment by Turnerj** [comment]
Actually I did just have one other thought though it really only works around it in our setup. We have a custom post-update hook in Composer to identify the exact version and write that somewhere??

Anyway, keen on your thoughts @3Dgoo :)

**Comment by 3Dgoo** [comment]
@Turnerj is this fixed as a part of #92 ?

**Comment by Turnerj** [comment]
That PR did cover important pieces to make our life implementing more advanced version support easier but doesn't cover the specific functionality.

My question to you: is it worth having support for dev versions with the update panel?
Should we just make a rule to never show the update panel if the current version is not a main release?
Should we try and implement some date-based rules between releases? (we would need to keep track of the date of the last update)

**Comment by 3Dgoo** [comment]
I do not think it is worth having support for dev versions in the update panel.

Yes, I think if current version is not a main release lets just hide the update panel.

That's what I think.

**Comment by Turnerj** [comment]
Cool. I'll implement the logic in the UpdatePanel for if the current version is not a main release, don't display the panel.
