### ISSUE TITLE
Automatically redirect search results when only one result is found

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#9]
When using the dashboard search if only one search result is found then automatically redirect to that result.

For example, if we search for "contact" and only one result is found across all the panels, automatically take the user to the contact edit page.

Also add a yml config variable to be able to turn this automatic redirection on and off.

- [x] Add automatic redirection programmring
- [x] Add yml config variable to turn this feature on and off
- [x] Add documentation describing this feature

**Comment by 3Dgoo** [comment]
Should this feature be on by default, or only enabled if the config variable is set to true? What do you think @RuthAdele ?

**Comment by RuthAdele** [comment]
I think it should only be enabled if the config variable is true. 
I think that there are arguments against this being good practice, as it changes the usual functionality, which a user may not expect or want.

**Comment by 3Dgoo** [comment]
Sounds good. 
I'm going to do this on a per class level and I'll leave it off by default. 
Thanks for your input.

**Comment by 3Dgoo** [comment]
The documentation example that needs to be added is this:

    Page:
      dashboard_automatic_search_redirect: true

Leaving this here so I don't forget.
