### ISSUE TITLE
Major update time delay

### ISSUE THREAD

**Issue by 3Dgoo** [plastyk/silverstripe-dashboard#91]
Hide major update available message for a certain length of time as defined by a config variable such as `delay_major_update_notification_for_x_time`.

**Comment by Turnerj** [comment]
Relates partially to one of the points in #89

**Comment by OldStarchy** [comment]
I'll start working on this one. Any thoughts amendments on the following idea?
* `ignore_major_updates: false`
The default
* `ignore_major_updates: 1 month`
Delay until the specified duration has passed before showing a notification. Time strings would be parsed by http://php.net/manual/en/dateinterval.createfromdatestring.php
* `ignore_major_updates: true`
Never show major version change notifications, just show the latest minor version available.

I guess there is a better config name, but that's what I've got for now.

**Comment by 3Dgoo** [comment]
I think `ignore_major_updates` is a good enough config name. Either that or `ignore_major_update`.

Your description on what to do sounds good. It's going to be tough. 

Keep in mind a date delay such as `1 month` will need to be 1 month from the first major release.
For example: 
Say the current SilverStripe version is `3.6.1`.
`ignore_major_updates` is set to `1 month`.
Version `4.0.0` was released 6 months ago.
Version `4.0.3` was released 3 days ago.
 
In this case we want to say that 4.0.3 is out.

**Comment by Turnerj** [comment]
With the change, we need to be careful not to over complicate the UpdatePanel. Right now, it is [one of the most complex sections of the code base according to Scrutinizer](https://scrutinizer-ci.com/g/plastyk/silverstripe-dashboard/code-structure).

Once we have the version and release date accessible in the code base though, we may actually be able to support the "dev" version numbers as their dates are continuously updated.

**Comment by OldStarchy** [comment]
https://github.com/aNickzz/silverstripe-dashboard/commit/f823118b3a265f3a17e9c6a5a5b7d4c7b4dd6c2c 
As discussed with @TurnerJ the UpdatePanel class is getting a bit big. Any thoughts on how it can be broken down / simplified?

**Comment by OldStarchy** [comment]
We also need a way to inject dummy version information for better testing, Taking a leaf out of `SS_DateTime`s book, we could add an `UpdatePanel::set_mock_version_list` function.

**Comment by Turnerj** [comment]
I propose we make a `VersionList` class with some of the functions we have currently on `UpdatePanel` (eg. `isNewestVersion`, `getVersionLevelDifference` etc). We can then add additional functions like checking if there is a new major version, filtering the versions etc. The constructor of the `VersionList` would be like `ArrayList`, taking an array of versions.

What `UpdatePanel` does then is create a `VersionList` object to do what it needs and populate it with version details from Packagist.

This allows us to keep `UpdatePanel` lean while also giving us an easier time performing unit tests on the core version logic.
